### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123@"
}

###

POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "anh",
  "password": "Admin123@",
  "name": "QA",
  "email": "anh@gmail.com"
}

###

