### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123@"
}

###

POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "anh",
  "password": "Admin123@",
  "name": "QA",
  "email": "anh@gmail.com"
}

###
GET http://localhost:8080/user/get-all

###

POST http://localhost:8080/products/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MiwibmFtZSI6IlBFUk1JU1NJT05fQUREX1BST0RVQ1QifSx7ImlkIjozLCJuYW1lIjoiUEVSTUlTU0lPTl9VUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjQsIm5hbWUiOiJQRVJNSVNTSU9OX0RFTEVURV9QUk9EVUNUIn0seyJpZCI6MSwibmFtZSI6IlJFQURfUEVSTUlTU0lPTiJ9XSwiaWF0IjoxNzM1OTc5OTg0LCJleHAiOjE3MzU5ODAxNjR9.zrZ6dJsVf-c12bGCCjRf6q06kRVY1P1wTDUiwm_V1-WHKJP5TxMiHNxlGbr7_3SNfdLlKdZRM0ssNWAFlEfCEQ

{
  "name": "milk",
  "price": 30000
}

###
GET http://localhost:8080/products/get-all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6NiwibmFtZSI6IkFERF9ESVNDT1VOVCJ9LHsiaWQiOjIsIm5hbWUiOiJBRERfUFJPRFVDVCJ9LHsiaWQiOjEwLCJuYW1lIjoiR0VUX1JFUE9SVCJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjEsIm5hbWUiOiJHRVRfUFJPRFVDVCJ9LHsiaWQiOjksIm5hbWUiOiJHRVRfSU5WT0lDRSJ9LHsiaWQiOjQsIm5hbWUiOiJVUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjUsIm5hbWUiOiJHRVRfRElTQ09VTlQifSx7ImlkIjo3LCJuYW1lIjoiR0VUX0hJU1RPUllfRElTQ09VTlQifSx7ImlkIjo4LCJuYW1lIjoiQUREX0lOVk9JQ0UifV0sImlhdCI6MTczNjY0NTA0OSwiZXhwIjoxNzM2NjQ1MjI5fQ.jWarIqRZrskGJdfpc5gw2N6V5kupnR73oC0ANx_B3zUuK0c4D57ztsQCF_CZIywTNCxNCuSjVTtIrBN0wMfoLg

###
POST http://localhost:8080/invoice/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MSwibmFtZSI6IkdFVF9QUk9EVUNUIn0seyJpZCI6MiwibmFtZSI6IkFERF9QUk9EVUNUIn0seyJpZCI6OSwibmFtZSI6IkdFVF9JTlZPSUNFIn0seyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NiwibmFtZSI6IkFERF9ESVNDT1VOVCJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjQsIm5hbWUiOiJVUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjgsIm5hbWUiOiJBRERfSU5WT0lDRSJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjUsIm5hbWUiOiJHRVRfRElTQ09VTlQifV0sImlhdCI6MTczNjY0NTI5OCwiZXhwIjoxNzM2NjQ1NDc4fQ.HtY9Kf5I6rb7LynqCxOSVslgMwDjbjzFPr5Opi9ImLXY2nKYAMjA3r6x3XZBHEF2oVweaCdrhLWunVMvUys-RA

{
  "customerEmail": "k@example.com",
  "customerName": "Customer Name",
  "invoiceDiscountId": 1,
  "items": [
    {
      "product": { "id": 1 },
      "quantity": 2,
      "productDiscountId": 1
    },
    {
      "product": { "id": 2 },
      "quantity": 3,
      "productDiscountId": 2
    }
  ]
}


###
GET http://localhost:8080/invoice

###
GET http://localhost:8080/report/revenue-by-month?startDate=2024-01-01&endDate=2025-01-20
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NCwibmFtZSI6IlVQREFURV9QUk9EVUNUIn0seyJpZCI6NSwibmFtZSI6IkdFVF9ESVNDT1VOVCJ9LHsiaWQiOjksIm5hbWUiOiJHRVRfSU5WT0lDRSJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjYsIm5hbWUiOiJBRERfRElTQ09VTlQifSx7ImlkIjoyLCJuYW1lIjoiQUREX1BST0RVQ1QifSx7ImlkIjoxLCJuYW1lIjoiR0VUX1BST0RVQ1QifSx7ImlkIjo4LCJuYW1lIjoiQUREX0lOVk9JQ0UifV0sImlhdCI6MTczNjY0NDIxMSwiZXhwIjoxNzM2NjQ0MzkxfQ.I8s36Vp_d-POFSHounA61Dkgr2zOJAt_jCEkLCaQrEERxDmLiuJ12NOe_zb6wasKKNtmbSaesZjZi5OVV24B1g

###
GET http://localhost:8080/report/revenue-by-quarter?startDate=2024-01-01&endDate=2025-01-05
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NCwibmFtZSI6IlVQREFURV9QUk9EVUNUIn0seyJpZCI6NSwibmFtZSI6IkdFVF9ESVNDT1VOVCJ9LHsiaWQiOjksIm5hbWUiOiJHRVRfSU5WT0lDRSJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjYsIm5hbWUiOiJBRERfRElTQ09VTlQifSx7ImlkIjoyLCJuYW1lIjoiQUREX1BST0RVQ1QifSx7ImlkIjoxLCJuYW1lIjoiR0VUX1BST0RVQ1QifSx7ImlkIjo4LCJuYW1lIjoiQUREX0lOVk9JQ0UifV0sImlhdCI6MTczNjY0NDIxMSwiZXhwIjoxNzM2NjQ0MzkxfQ.I8s36Vp_d-POFSHounA61Dkgr2zOJAt_jCEkLCaQrEERxDmLiuJ12NOe_zb6wasKKNtmbSaesZjZi5OVV24B1g

###
GET http://localhost:8080/report/revenue-by-year?startDate=2024-01-01&endDate=2025-01-05
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NCwibmFtZSI6IlVQREFURV9QUk9EVUNUIn0seyJpZCI6NSwibmFtZSI6IkdFVF9ESVNDT1VOVCJ9LHsiaWQiOjksIm5hbWUiOiJHRVRfSU5WT0lDRSJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjYsIm5hbWUiOiJBRERfRElTQ09VTlQifSx7ImlkIjoyLCJuYW1lIjoiQUREX1BST0RVQ1QifSx7ImlkIjoxLCJuYW1lIjoiR0VUX1BST0RVQ1QifSx7ImlkIjo4LCJuYW1lIjoiQUREX0lOVk9JQ0UifV0sImlhdCI6MTczNjY0NDIxMSwiZXhwIjoxNzM2NjQ0MzkxfQ.I8s36Vp_d-POFSHounA61Dkgr2zOJAt_jCEkLCaQrEERxDmLiuJ12NOe_zb6wasKKNtmbSaesZjZi5OVV24B1g

###
GET http://localhost:8080/discount-history/invoice/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MSwibmFtZSI6IkdFVF9QUk9EVUNUIn0seyJpZCI6MiwibmFtZSI6IkFERF9QUk9EVUNUIn0seyJpZCI6OSwibmFtZSI6IkdFVF9JTlZPSUNFIn0seyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NiwibmFtZSI6IkFERF9ESVNDT1VOVCJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjQsIm5hbWUiOiJVUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjgsIm5hbWUiOiJBRERfSU5WT0lDRSJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjUsIm5hbWUiOiJHRVRfRElTQ09VTlQifV0sImlhdCI6MTczNjY0NTI5OCwiZXhwIjoxNzM2NjQ1NDc4fQ.HtY9Kf5I6rb7LynqCxOSVslgMwDjbjzFPr5Opi9ImLXY2nKYAMjA3r6x3XZBHEF2oVweaCdrhLWunVMvUys-RA

###
GET  http://localhost:8080/discount
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MSwibmFtZSI6IkdFVF9QUk9EVUNUIn0seyJpZCI6MiwibmFtZSI6IkFERF9QUk9EVUNUIn0seyJpZCI6OSwibmFtZSI6IkdFVF9JTlZPSUNFIn0seyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NiwibmFtZSI6IkFERF9ESVNDT1VOVCJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjQsIm5hbWUiOiJVUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjgsIm5hbWUiOiJBRERfSU5WT0lDRSJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjUsIm5hbWUiOiJHRVRfRElTQ09VTlQifV0sImlhdCI6MTczNjY0NTI5OCwiZXhwIjoxNzM2NjQ1NDc4fQ.HtY9Kf5I6rb7LynqCxOSVslgMwDjbjzFPr5Opi9ImLXY2nKYAMjA3r6x3XZBHEF2oVweaCdrhLWunVMvUys-RA

###
POST http://localhost:8080/discount/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MSwibmFtZSI6IkdFVF9QUk9EVUNUIn0seyJpZCI6MiwibmFtZSI6IkFERF9QUk9EVUNUIn0seyJpZCI6OSwibmFtZSI6IkdFVF9JTlZPSUNFIn0seyJpZCI6MTAsIm5hbWUiOiJHRVRfUkVQT1JUIn0seyJpZCI6NiwibmFtZSI6IkFERF9ESVNDT1VOVCJ9LHsiaWQiOjcsIm5hbWUiOiJHRVRfSElTVE9SWV9ESVNDT1VOVCJ9LHsiaWQiOjQsIm5hbWUiOiJVUERBVEVfUFJPRFVDVCJ9LHsiaWQiOjgsIm5hbWUiOiJBRERfSU5WT0lDRSJ9LHsiaWQiOjMsIm5hbWUiOiJERUxFVEVfUFJPRFVDVCJ9LHsiaWQiOjUsIm5hbWUiOiJHRVRfRElTQ09VTlQifV0sImlhdCI6MTczNjY0NTI5OCwiZXhwIjoxNzM2NjQ1NDc4fQ.HtY9Kf5I6rb7LynqCxOSVslgMwDjbjzFPr5Opi9ImLXY2nKYAMjA3r6x3XZBHEF2oVweaCdrhLWunVMvUys-RA

{
  "value": 10000,
  "type": "AMOUNT"
}

###
GET http://localhost:8080/permission

###

POST http://localhost:8080/permission/add
Content-Type: application/json

{
  "name": "ADD_PERMISSION"
}

###
POST http://localhost:8080/role/add
Content-Type: application/json

{
  "role": "Sale",
  "description": "",
  "permissions": [
    {"id": 2}
  ]
}

###
GET http://localhost:8080/role